Combine all repo changes into a single job
When any step in this job fails, the repo is never pushed back. This should make sure the any failure will result in no actual changes to the repo.

diff --git a/.github/workflows/release_github.yml b/.github/workflows/release_github.yml
--- a/.github/workflows/release_github.yml
+++ b/.github/workflows/release_github.yml
@@ -23,8 +23,8 @@ permissions:
   repository-projects: read
 
 jobs:
-  check_main:
-    name: Check that branch is not main
+  checks:
+    name: Check requirements
     runs-on: "ubuntu-latest"
     steps:
       - name: Fail if main branch was selected
@@ -32,9 +32,35 @@ jobs:
         run: |
           echo "Cannot release from main branch, please select valid release branch."
           exit 1
+      - name: Check GitHub token validity
+        run: |
+          echo "-- Validating GitHub Token"
+          status_code=$(curl -o /dev/null -s -w "%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user)
+          if [ "$status_code" -ne 200 ]; then
+            echo "Error: GitHub token is invalid or expired. Please update your token in secrets."
+            echo "Instructions can be found at: https://github.com/EIT-ALIVE/eitprocessing/blob/main/README.dev.md#updating-the-token"
+            exit 1
+          else
+            echo "GitHub token is valid."
+          fi
+      - name: Check if PR base is main
+        if: ${{ github.ref_name != 'develop' }}
+        run: |
+          if [ $(gh pr view ${{ github.ref_name }} --json baseRefName -q ".baseRefName" != "main") ]; then
+            echo "Error: PR base is not main."
+            exit 1
+          fi
+      - name: Check if PR is mergeable
+        if: ${{ github.ref_name != 'develop' }}
+        run: |
+          if [ $(gh pr view ${{ github.ref_name }} --json mergeable -q ".mergeable") != "MERGEABLE" ]; then 
+            echo "Error: PR is not mergeable."
+            exit 1
+          fi
+
 
   test_python_releases:
-    needs: check_main
+    needs: checks
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -62,26 +88,14 @@ jobs:
       - name: Build eitprocessing
         run: python3 -m build
 
-  merge_pr:
-    name: Merge the PR into main
-    if: ${{ github.ref_name != 'develop' }}
+  merge_and_bump: 
+    name: Merge the changes into main and bump the version
     needs: test_python_releases
     runs-on: ubuntu-latest
+    outputs:
+      new-version: ${{ steps.bump.outputs.current-version }}
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Set PR base to main and merge
-        run: |
-          gh pr edit ${{ github.ref_name }} --base main
-          gh pr merge ${{ github.ref_name }} --merge --admin
-
-  merge_develop:
-    name: Merge develop into main
-    if: ${{ github.ref_name == 'develop'}}
-    needs: test_python_releases
-    runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -93,44 +107,22 @@ jobs:
           git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
           git config user.name "GitHub Actions"
           git config -l
-      - name: Merge changes into main
+
+      - name: Merge branch into main
         run: |
           git switch main
-          git branch ${{ github.ref_name }} origin/${{ github.ref_name }} 
-          git merge ${{ github.ref_name }} --no-ff --no-edit
-      - name: Push changes to GitHub
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          force: true
-
-  bump_version:
-    name: Bump the version
-    needs: [merge_pr, merge_develop]
-    if: ${{ always() && (needs.merge_pr.result == 'success' || needs.merge_develop.result == 'success') }}
-    runs-on: "ubuntu-latest"
-    outputs:
-      new-version: ${{ steps.bump.outputs.current-version }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          ref: main
-      - name: Setting up git config
-        shell: bash
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
-          git config user.name "GitHub Actions"
-          git config -l
+          git branch -f develop origin/develop 
+          git merge develop --no-ff --no-edit
+    
       - name: Install Python
         uses: actions/setup-python@v5.1.1
         with:
-          python-version: "3.12"
+          python-version: '3.12'
+  
       - name: Install bump-my-version
         shell: bash
         run: pip install "bump-my-version==0.28.1"
+        
       - name: Pass Inputs to Shell
         id: bump
         shell: bash
@@ -139,26 +131,38 @@ jobs:
           bump-my-version bump ${{ inputs.version_level }} --commit --tag
           ([[ $? -gt 0 ]] && echo "bumped=false" || echo "bumped=true") >> $GITHUB_OUTPUT
           echo "current-version=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT
-      - name: Push changes to GitHub
-        uses: ad-m/github-push-action@master
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          force: true
       - name: Fail if bumping failes
         if: steps.bump.outputs.bumped == 'false'
         run: |
           echo "Bumping failed."
+          git reset --hard HEAD^
           exit 1
       - name: Check new version number
         if: steps.bump.outputs.bumped == 'true'
         run: |
           echo "Version was bumped from ${{ steps.bump.outputs.previous-version }} to ${{ steps.bump.outputs.current-version }}!"
 
+      - name: Merge main into develop
+        run: |
+          git checkout develop
+          git merge main --no-ff --no-edit
+      
+      - name: Push changes to GitHub
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: develop
+
+      - name: Push changes to GitHub
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          branch: main
+  
   github_release:
     name: Create a draft GitHub release
-    needs: bump_version
-    if: ${{ always() && needs.bump_version.result == 'success' }}
-    runs-on: "ubuntu-latest"
+    needs: merge_and_bump
+    runs-on: 'ubuntu-latest'
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -169,8 +173,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          gh release create v${{ needs.bump_version.outputs.new-version }} \
-              --title="Release v${{ needs.bump_version.outputs.new-version }}" \
+          gh release create v${{ needs.merge_and_bump.outputs.new-version }} \
+              --title="Release v${{ needs.merge_and_bump.outputs.new-version }}" \
               --generate-notes \
               --draft
 
@@ -185,16 +189,7 @@ jobs:
         with:
           ref: develop
           fetch-depth: 0
-      - name: Configure git
-        run: |
-          git config user.email "actions@github.com"
-          git config user.name "GitHub Actions"
-          git pull
-      - name: Merge main into develop
-        run: |
-          git branch main origin/main
-          git merge main --no-ff --no-edit
-          git push
+      
       - name: Remove PR branch
         if: ${{ github.ref_name != 'develop' }}
         uses: dawidd6/action-delete-branch@v3
